# Generated by Django 3.1.2 on 2020-10-07 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('C', 'Coleccionista'), ('V', 'Vendedor'), ('M', 'ColeccionistaVendedor')], default='C', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Coleccion'), ('V', 'Venta')], default='C', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Tipo',
            },
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('anverso', models.ImageField(upload_to='media/coleccion', verbose_name='Imagen')),
                ('reverso', models.ImageField(upload_to='media/coleccion', verbose_name='Imagen')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionColeccion.categoria')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionColeccion.tipo')),
            ],
            options={
                'verbose_name_plural': 'Pieza',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=102, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Maculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'No definir')], default='N', max_length=1)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='media/profile', verbose_name='Imagen')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionColeccion.rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_c', models.DateTimeField()),
                ('id_pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionColeccion.pieza')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionColeccion.perfil')),
            ],
            options={
                'verbose_name_plural': 'Colección',
            },
        ),
    ]
