# Generated by Django 3.1.2 on 2020-10-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionColeccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'No definir')], default='N', max_length=1),
        ),
    ]
